=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/devices.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "Devices data",
  "description": "Devices data - schema (devices data model)",
  "type": "object",
  "required": [ "version", "vendor", "devices" ],
  "additionalProperties": false,
  "properties": {
    "copyright": {
      "description": "Devices data - Copyright 2022-2025 NXP",
      "type": "string"
    },
    "license": {
      "description": "Devices data - SPDX-License-Identifier: BSD-3-Clause",
      "type": "string"
    },
    "version": {
      "description": "Devices data - schema version (recommended 1.1.1)",
      "enum": ["1.1.1", "1.1.0", "1.0.0", "0.0.1" ]
    },
    "vendor": {
      "description": "Devices data - vendor",
      "type": "string"
    },
    "devices": {
      "description": "List of devices",
      "type": "array",
      "items": {
        "description": "Device data",
        "type": "object",
        "required": [ "board", "device", "debug" ],
        "additionalProperties": false,
        "properties": {
          "board": {
            "description": "Board name. It can be an empty string if board name is not needed.",
            "$comment": "key_b - (SDK: boards->board->name [+ other_specific_info (fuse_config, custom_flash ...)])",
            "type": "string"
          },
          "device": {
            "description": "Device specific information",
            "type": "object",
            "required": ["family", "memory", "cores" ],
            "anyOf" :[
              {"required" : ["id"]},
              {"required" : ["name"]}
            ],
            "additionalProperties": false,
            "properties": {
              "id": {
                "description": "Device id",
                "$comment": "key_d1 - (SDK: devices->device->id). unique key = (key_b + key_d1) = (board + device->id)",
                "type": "string"
              },
              "name": {
                "description": "User-friendly device name",
                "$comment": "key_d2. unique key = (key_b + key_d2) = (board + device->name)",
                "type": "string"
              },
              "family": {
                "description": "Device family",
                "$comment": "(SDK: devices->device->family)",
                "type": "string"
              },
              "memory": {
                "description": "Device memory map - flash/ram regions",
                "$comment": "(SDK: (devices->device)/(boards->board)->memory->memoryBlock entries, (devices->device)/(boards->board)->debug_configurations...->drivers)",
                "type": "array",
                "minItems": 1,
                "items": {
                  "description": "Memory region info",
                  "type": "object",
                  "required": [ "location", "size", "type" ],
                  "additionalProperties": false,
                  "properties": {
                    "location": {
                      "description": "Start address (format: hex)",
                      "type": "string",
                      "pattern": "^0x([a-fA-F0-9])+$"
                    },
                    "size": {
                      "description": "Region size (format: hex)",
                      "type": "string",
                      "pattern": "^0x([a-fA-F0-9])+$"
                    },
                    "type": {
                      "description": "Memory type",
                      "enum": [ "Flash", "ExtFlash", "RAM" ]
                    },
                    "flash-driver": {
                      "description": "Flash driver file name (*.cfx)",
                      "$comment": "(SDK: (devices->device)/(boards->board)->debug_configurations...->drivers... driverBinary...files mask)",
                      "type": "string"
                    },
                    "core-name": {
                      "description": "Core specific memory region. If needed, must be one of the keys from devices.cores",
                      "type": "string"
                    }
                  }
                }
              },
              "cores": {
                "description": "Cores topology (ordered by access port or TAP)",
                "type": "array",
                "minItems": 1,
                "uniqueItems": true,
                "items": {
                  "description": "Core information",
                  "type": "object",
                  "required": [ "name" ],
                  "additionalProperties": false,
                  "properties": {
                    "name": {
                      "description": "Core name, unique per device",
                      "$comment": "(SDK: devices->device->core->name or devices->device->core->type for single core devices)",
                      "type": "string",
                      "format": "^[A-Za-z0-9_\\-]$"
                    },
                    "type": {
                      "description": "Core type",
                      "$comment": "(SDK: devices->device->core->type)",
                      "type": "string"
                    },
                    "primary": {
                      "description": "Is primary boot core. Only one core is allowed to be a primary boot core.",
                      "$comment": "(SDK: devices->device->core->boot_role)",
                      "type": "boolean"
                    },
                    "index": {
                      "description": "Core index, used to specify a custom value or to change the default index. (format: n or n_ap:n_tap. Where n_ap = n divided by 16, n_tap = n_t modulo 16. n, n_ap, n_tap are decimal numbers.)",
                      "$comment": "(SDK: not available in the manifest data) (launcher: to be added for the parts that require this)",
                      "type": "string",
                      "examples": ["1", "1:2"]
                    }
                  }
                }
              }
            }
          },
          "debug": {
            "description": "Debug specific information",
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "core-options": {
                "description": "Debug specific core options. The key must be a core name from device.cores",
                "type": "object",
                "patternProperties": {
                  "^[A-Za-z0-9_\\-]$": {
                    "description": "Debug information for this core",
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                      "cachelib": {
                        "description": "I-Cache/D-Cache handler library",
                        "$comment": "(SDK: devices->device->debug_configurations->params: misc.options...--cachelib <lib>.so)",
                        "type": "string"
                      }
                    }
                  }
                }
              },
              "connect-reset": {
                "description": "Reset method on initial connection",
                "$comment": "(SDK: devices->device->debug_configurations->params: vector.catch. Set this to default if vector.catch=true, ignored otherwise.) (launcher/stub: --vc --connect-reset <method>)",
                "enum": [ "system", "core", "default" ]
              },
              "flash-driver-reset": {
                "description": "Reset method before running the RAM-loaded flash driver",
                "$comment": "(SDK: devices->device->debug_configurations->params: flash.driver.reset)",
                "enum": [ "system", "core", "soft" ]
              },
              "reset": {
                "description": "Reset method used to start the image loaded into flash memory",
                "$comment": "(SDK: do not add this if not explicitly set in the manifest data)",
                "enum": [ "system", "core", "soft" ]
              },
              "preattach-script": {
                "description": "Pre-attach script",
                "$comment": "(SDK: not available in the manifest data) (launcher: to be added for the parts that require this)",
                "type": "string"
              },
              "preconnect-script": {
                "description": "Pre-connect script",
                "$comment": "(SDK: not available in the manifest data) (launcher adds this in the process script)",
                "type": "string"
              },
              "connect-script": {
                "description": "Connect script",
                "$comment": "(SDK: devices->device->debug_configurations->params: internal.connect.script)",
                "type": "string"
              },
              "reset-script": {
                "description": "Reset script",
                "$comment": "(SDK: devices->device->debug_configurations->params: internal.reset.script)",
                "type": "string"
              },
              "masserase-script": {
                "description": "Mass erase script",
                "$comment": "(SDK: not available in the manifest data) (launcher: to be added for the parts that require this)",
                "type": "string"
              },
              "bootromstall": {
                "description": "BootROM stall address (format: hex)",
                "$comment": "(SDK: devices->device->debug_configurations->params: misc.options...--bootromstall <addr>)",
                "type": "string",
                "pattern": "^0x([a-fA-F0-9])+$"
              },
              "romstalldelay": {
                "description": "BootROM stall delay in milliseconds",
                "$comment": "(SDK: devices->device->debug_configurations->params: misc.options...--romstalldelay <ms>)",
                "type": "integer",
                "minimum": 0,
                "examples": [200]
              },
              "no-flash-hashing": {
                "description": "Disable flash hashing (enabled by default)",
                "$comment": "(SDK: not available in the manifest data) (launcher: to be added for the parts that require this)",
                "type": "boolean",
                "default": false
              },
              "no-packed": {
                "description": "Debug Access Port (DAP) does not support packed transfers",
                "$comment": "(SDK: devices->device->debug_configurations->params: misc.options...--no-packed)",
                "type": "boolean",
                "default": false
              },
              "dapstride": {
                "description": "DAP stride",
                "$comment": "(SDK: devices->device->debug_configurations->params: misc.options...--dapstride <value>)",
                "enum": [ "auto", "standard", "long", "short" ]
              },
              "apindex-limit": {
                "description": "DAP AP index limit",
                "$comment": "(SDK: devices->device->metadataSet->metadata->key=server.APLimit)",
                "type": "integer",
                "minimum": 0
              },
              "apindexes-allowed": {
                "description": "TODO: A list of DAP AP indexes allowed (not yet supported in stub)",
                "type": "array",
                "items": {
                  "description": "DAP AP index",
                  "type": "integer",
                  "minimum": 0
                }
              },
              "protocol": {
                "description": "Debug protocol",
                "$comment": "(SDK: devices->device->debug_configurations->params...internal.wiretype)",
                "enum": [ "swd", "jtag" ],
                "default": "swd"
              },
              "swo": {
                "description": "Has SWO",
                "$comment": "(SDK: devices->device->debug_configurations->params...internal.has_swo)",
                "type": "boolean"
              },
              "wirespeed": {
                "description": "Wire speed in Hz",
                "$comment": "(SDK: not available in the manifest data) (launcher: to be added for the parts that require this)",
                "type": "integer",
                "minimum": 0
              },
              "bootconfigs": {
                "description": "Boot configurations (name:<data> pairs) aimed to be used with MCU-Link on-board probes. <data> is a string of 4 characters ('x', '1' or '0') describing how each ISP_CTRL[3..0] pin should be handled.",
                "$comment": "(SDK: not yet available in the manifest data)",
                "type": "object",
                "patternProperties": {
                  "^[A-Za-z0-9_-]*$": {
                    "description": "<data> for this boot configuration name",
                    "type": "string",
                    "pattern": "^[x01]{4}$"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/HVP-KV58F.json
{
  "copyright": "Copyright 2023-2025 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "HVP-KV58F",
      "device": {
        "id": "MKV58F1M0xxx24",
        "name": "MKV58F24",
        "family": "KV5x",
        "memory": [
          {
            "location": "0x10000000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "FTFE_8K_KV.cfx"
          },
          {
            "location": "0x20000000",
            "size": "0x00020000",
            "type": "RAM"
          },
          {
            "location": "0x2f000000",
            "size": "0x00010000",
            "type": "RAM"
          },
          {
            "location": "0x00000000",
            "size": "0x00010000",
            "type": "RAM"
          },
          {
            "location": "0x18000000",
            "size": "0x00001000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm7",
            "name": "cm7"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "reset": "core",
        "connect-script": "kinetisconnect.scp",
        "masserase-script": "kinetismasserase.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/TWR-K80F150M.json
{
  "copyright": "Copyright 2023-2024 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "TWR-K80F150M",
      "device": {
        "id": "MK80FN256xxx15",
        "name": "MK80F25615",
        "family": "K8x",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00040000",
            "type": "Flash",
            "flash-driver": "FTFA_4K.cfx"
          },
          {
            "location": "0x20000000",
            "size": "0x00030000",
            "type": "RAM"
          },
          {
            "location": "0x1fff0000",
            "size": "0x00010000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm4",
            "name": "cm4"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "connect-script": "kinetisconnect.scp",
        "masserase-script": "kinetismasserase.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/MCXN527.json
{
  "copyright": "Copyright 2025 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "",
      "device": {
        "id": "MCXN527",
        "name": "MCXN527",
        "family": "MCXN5XX",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "MCXNxxx.cfx"
          },
          {
            "location": "0x10000000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "MCXNxxx_S.cfx"
          },
          {
            "location": "0x00100000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "MCXNxxx.cfx"
          },
          {
            "location": "0x10100000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "MCXNxxx_S.cfx"
          },
          {
            "location": "0x20000000",
            "size": "0x00060000",
            "type": "RAM"
          },
          {
            "location": "0x04000000",
            "size": "0x00018000",
            "type": "RAM"
          },
          {
            "location": "0x20060000",
            "size": "0x00008000",
            "type": "RAM"
          },
          {
            "location": "0x400ba000",
            "size": "0x00001000",
            "type": "RAM"
          },
          {
            "location": "0x30000000",
            "size": "0x00060000",
            "type": "RAM"
          },
          {
            "location": "0x14000000",
            "size": "0x00018000",
            "type": "RAM"
          },
          {
            "location": "0x30060000",
            "size": "0x00008000",
            "type": "RAM"
          },
          {
            "location": "0x500BA000",
            "size": "0x00001000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm33",
            "name": "cm33_core0",
            "primary": true
          },
          {
            "type": "cm33_nodsp",
            "name": "cm33_core1"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "bootromstall": "0x50000040",
        "romstalldelay": 600,
        "preconnect-script": "LS_preconnect_MCXN5XX.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/FRDM-MCXA366.json
{
  "copyright": "Copyright 2025 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "FRDM-MCXA366",
      "device": {
        "id": "MCXA366",
        "name": "MCXA366",
        "family": "MCXA3XX",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00100000",
            "type": "Flash",
            "flash-driver": "MCXA3xx.cfx"
          },
          {
            "location": "0x20000000",
            "size": "0x0003c000",
            "type": "RAM"
          },
          {
            "location": "0x04002000",
            "size": "0x00002000",
            "type": "RAM"
          },
          {
            "location": "0x04000000",
            "size": "0x00002000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm33",
            "name": "cm33"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "bootromstall": "0x4009123C",
        "preconnect-script": "LS_preconnect_MCXA3XX.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/HVP-KE18F.json
{
  "copyright": "Copyright 2023-2024 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "HVP-KE18F",
      "device": {
        "id": "MKE18F512xxx16",
        "name": "MKE18F16",
        "family": "KE1x",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00080000",
            "type": "Flash",
            "flash-driver": "FTFE_4K.cfx"
          },
          {
            "location": "0x20000000",
            "size": "0x00008000",
            "type": "RAM"
          },
          {
            "location": "0x1fff8000",
            "size": "0x00008000",
            "type": "RAM"
          },
          {
            "location": "0x14000000",
            "size": "0x00001000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm4",
            "name": "cm4"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "connect-script": "kinetisconnect.scp",
        "masserase-script": "kinetismasserase.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/K32L2B11xxxxA.json
{
  "copyright": "Copyright 2025 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "",
      "device": {
        "id": "K32L2B11xxxxA",
        "name": "K32L2B11A",
        "family": "K32L2B11A",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00010000",
            "type": "Flash",
            "flash-driver": "K32L2B.cfx"
          },
          {
            "location": "0x1fffe000",
            "size": "0x00008000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm0plus",
            "name": "cm0plus"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": false,
        "connect-script": "kinetisconnect.scp",
        "masserase-script": "kinetismasserase.scp"
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/MIMX9311xxxxM.json
{
  "copyright": "Copyright 2025 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "",
      "device": {
        "id": "MIMX9311xxxxM",
        "name": "MIMX9311",
        "family": "MIMX93xx",
        "memory": [
          {
            "location": "0x20000000",
            "size": "0x00020000",
            "type": "RAM"
          },
          {
            "location": "0x0ffe0000",
            "size": "0x00020000",
            "type": "RAM"
          },
          {
            "location": "0x20020000",
            "size": "0x00020000",
            "type": "RAM"
          },
          {
            "location": "0x20480000",
            "size": "0x000A0000",
            "type": "RAM"
          },
          {
            "location": "0x80000000",
            "size": "0x40000000",
            "type": "RAM"
          }
        ],
        "cores": [
          {
            "type": "cm33",
            "name": "cm33",
            "index": "3"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "connect-script": "IMX93_connect_M33.scp",
        "reset-script": "IMX93_reset_M33.scp",
        "no-packed": true,
        "dapstride": "short",
        "apindex-limit": 4
      }
    }
  ]
}

=== solfamila/rt595_sweep_bundle/.local/linkserver/extracted/flatten_LinkServer_25.12.83.pkg/Payload/devices/LPCXpresso54S018.json
{
  "copyright": "Copyright 2023-2024 NXP",
  "license": "SPDX-License-Identifier: BSD-3-Clause",
  "version": "1.1.0",
  "vendor": "NXP",
  "devices": [
    {
      "board": "LPCXpresso54S018",
      "device": {
        "id": "LPC54S018",
        "name": "LPC54S018",
        "family": "LPC540xx",
        "memory": [
          {
            "location": "0x00000000",
            "size": "0x00030000",
            "type": "RAM"
          },
          {
            "location": "0x20000000",
            "size": "0x00028000",
            "type": "RAM"
          },
          {
            "location": "0x40100000",
            "size": "0x00002000",
            "type": "RAM"
          },
          {
            "location": "0x10000000",
            "size": "0x01000000",
            "type": "Flash",
            "flash-driver": "LPC540xx_SPIFI_SFDP.cfx"
          }
        ],
        "cores": [
          {
            "type": "cm4",
            "name": "cm4"
          }
        ]
      },
      "debug": {
        "protocol": "swd",
        "swo": true,
        "bootromstall": "0x40000040",
        "connect-reset": "default",
        "flash-driver-reset": "soft"
      }
    }
  ]
}
